all:
	cd blob && make
	cd console && make
	cd fs && make
	cd http && make
	cd process && make 
	cd sh && make

clean:
	cd blob && make clean
	cd console && make clean
	cd fs && make clean
	cd http && make clean
	cd process && make clean
	cd sh && make clean
